parameters:
- name: environment
  type: string
- name: serviceConnection
  type: string
- name: uiWebAppName
  type: string
- name: azureBicepMain
  type: string
- name: stageName
  type: string
- name: dependsOn
  type: object

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy ${{ parameters.environment }} environment'
  condition: eq(variables['environment'], '${{ parameters.environment }}')
  variables:
    - group: ${{ parameters.environment }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
    - job: DeployInfra${{ parameters.environment }}
      displayName: 'Deploy Web Infrastructure'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
          fetchDepth: 1
          persistCredentials: true

        - task: AzureCLI@2
          displayName: 'Validate Web Infrastructure (Bicep What-If)'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az deployment group validate \
                --resource-group $(AZURE_RESOURCE_GROUP) \
                --template-file ${{ parameters.azureBicepMain }} \
                --parameters ./infra/frontend/${{ parameters.environment }}.bicepparam environmentName=${{ parameters.environment }}

        - task: AzureCLI@2
          displayName: 'Deploy Web Infrastructure (Bicep Create)'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az deployment group create \
                --resource-group $(AZURE_RESOURCE_GROUP) \
                --template-file ${{ parameters.azureBicepMain }} \
                --parameters ./infra/frontend/${{ parameters.environment }}.bicepparam environmentName=${{ parameters.environment }}

        - script: |
            echo "✅ Web Infrastructure Deployment: Completed"
            echo "📋 Environment: ${{ parameters.environment }}"
            echo "📋 Resource Group: $(AZURE_RESOURCE_GROUP)"
          displayName: 'Print Infra Deployment Summary'

    - job: DeployApp${{ parameters.environment }}
      displayName: 'Deploy AI-One Web App'
      dependsOn: DeployInfra${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
          fetchDepth: 1
          persistCredentials: true

        - task: DownloadPipelineArtifact@2
          displayName: 'Download AI-One  Web App Artifact'
          inputs:
            artifact: 'agile-chat-web'
            path: '$(Build.ArtifactStagingDirectory)'

        - task: AzureWebApp@1
          displayName: 'Deploy AI-One Web App'
          inputs:
            appType: webAppLinux
            azureSubscription: ${{ parameters.serviceConnection }}
            appName: ${{ parameters.uiWebAppName }}
            package: '$(Build.ArtifactStagingDirectory)/release.zip'
            runtimeStack: 'NODE|22-lts'

        - script: |
            echo "✅ Web Application Deployment: Completed"
            echo "🎉 Frontend deployment successful!"
            echo "📋 Environment: ${{ parameters.environment }}"
            echo "📋 App Name: ${{ parameters.uiWebAppName }}"
          displayName: 'Print App Deployment Summary'
