trigger: none

parameters:
  - name: environment
    type: string
    default: dev
    displayName: "Select the environment to deploy the platform infrastructure"
    values:
      - dev
      - tst
      - uat
      - prod

variables:
  - name: environment
    value: ${{ parameters.environment }}
  - name: AZURE_BICEP_CORE
    value: "./infra/platform/core/main.bicep"
  - name: AZURE_BICEP_AI
    value: "./infra/platform/ai/main.bicep"

  # Environment-specific service connections
  - name: SERVICE_CONNECTION_DEV
    value: "dev-service-connection"
  - name: SERVICE_CONNECTION_TST
    value: "tst-service-connection"
  - name: SERVICE_CONNECTION_UAT
    value: "uat-service-connection"
  - name: SERVICE_CONNECTION_PROD
    value: "prod-service-connection"

stages:
  - template: templates/deploy-platform-template.yml
    parameters:
      stageName: DeployPlatformDev
      environment: dev
      serviceConnection: $(SERVICE_CONNECTION_DEV)
      azureBicepCore: $(AZURE_BICEP_CORE)
      azureBicepAi: $(AZURE_BICEP_AI)
      dependsOn: null

  - template: templates/deploy-platform-template.yml
    parameters:
      stageName: DeployPlatformTst
      environment: tst
      serviceConnection: $(SERVICE_CONNECTION_TST)
      azureBicepCore: $(AZURE_BICEP_CORE)
      azureBicepAi: $(AZURE_BICEP_AI)
      dependsOn: DeployPlatformDev

  - template: templates/deploy-platform-template.yml
    parameters:
      stageName: DeployPlatformUat
      environment: uat
      serviceConnection: $(SERVICE_CONNECTION_UAT)
      azureBicepCore: $(AZURE_BICEP_CORE)
      azureBicepAi: $(AZURE_BICEP_AI)
      dependsOn: DeployPlatformTst

  - template: templates/deploy-platform-template.yml
    parameters:
      stageName: DeployPlatformProd
      environment: prod
      serviceConnection: $(SERVICE_CONNECTION_PROD)
      azureBicepCore: $(AZURE_BICEP_CORE)
      azureBicepAi: $(AZURE_BICEP_AI)
      dependsOn: DeployPlatformUat
