trigger: none

parameters:
  - name: environment
    type: string
    default: dev
    displayName: "Select the environment to deploy"
    values:
      - dev
      - tst
      - uat
      - prod

variables:
  - name: environment
    value: ${{ parameters.environment }}
  - name: AZURE_BICEP_MAIN
    value: "./infra/networking/main.bicep"

  # Environment-specific service connections
  - name: SERVICE_CONNECTION_DEV
    value: "dev-service-connection"
  - name: SERVICE_CONNECTION_TST
    value: "tst-service-connection"
  - name: SERVICE_CONNECTION_UAT
    value: "uat-service-connection"
  - name: SERVICE_CONNECTION_PROD
    value: "prod-service-connection"

stages:
  - template: templates/deploy-template.yml
    parameters:
      dependsOn: null
      stageName: DeployNetworkDev
      environment: dev
      serviceConnection: $(SERVICE_CONNECTION_DEV)
      azureBicepMain: $(AZURE_BICEP_MAIN)
      parameterFilePath: "./infra/networking/dev.bicepparam"

  - template: templates/deploy-template.yml
    parameters:
      dependsOn: DeployNetworkDev
      stageName: DeployNetworkTst
      environment: tst
      serviceConnection: $(SERVICE_CONNECTION_TST)
      azureBicepMain: $(AZURE_BICEP_MAIN)
      parameterFilePath: "./infra/networking/tst.bicepparam"

  - template: templates/deploy-template.yml
    parameters:
      dependsOn: DeployNetworkTst
      stageName: DeployNetworkUat
      environment: uat
      serviceConnection: $(SERVICE_CONNECTION_UAT)
      azureBicepMain: $(AZURE_BICEP_MAIN)
      parameterFilePath: "./infra/networking/uat.bicepparam"

  - template: templates/deploy-template.yml
    parameters:
      dependsOn: DeployNetworkUat
      stageName: DeployNetworkProd
      environment: prod
      serviceConnection: $(SERVICE_CONNECTION_PROD)
      azureBicepMain: $(AZURE_BICEP_MAIN)
      parameterFilePath: "./infra/networking/prod.bicepparam"
