trigger: none

parameters:
- name: environment_name
  type: string
  default: 'dev'
  displayName: 'Select the application environment name - used to name resources'
  values:
  - 'dev'
  - 'tst'
  - 'uat'
  - 'prod'

- name: asp_core_environment
  type: string
  default: 'Development'
  displayName: 'Select the ASP Core deployment environment'
  values:
  - 'Development'
  - 'Test'
  - 'UAT'
  - 'Production'

- name: project_name
  type: string
  default: 'ag-aione'
  displayName: 'Enter the Name of the project'

- name: azure_location
  type: string
  default: 'australiaeast'
  displayName: 'Select the Azure deployment location'
  values:
  - 'australiaeast'
  - 'australiasoutheast'

- name: set_kv_function_app_permissions
  type: boolean
  default: false
  displayName: 'Deploy and Assign Keyvault Web App Permissions?'

- name: semantic_search_sku
  type: string
  default: 'standard'
  displayName: 'Select the Azure Search AI Semantic Search Sku'
  values:
  - 'disabled'
  - 'free'
  - 'standard'

variables:
- name: AZURE_BICEP_MAIN
  value: './infra/main.bicep'
# SERVICE_CONNECTION_NAME
# AZURE_SUBSCRIPTION_ID
# AZURE_CLIENT_ID
# AZURE_TENANT_ID
# AZURE_RESOURCE_GROUP
# APIM_ENDPOINT_OVERRIDE (optional but needed to be defined in variables as empty)
# APIM_EMBEDDINGS_ENDPOINT_OVERRIDE (optional but needed to be defined in variables as empty)

stages:
- stage: DeployInfrastructure
  displayName: 'Deploy Azure Infrastructure'
  jobs:
  - job: InfraDeploy
    displayName: 'Deploy Bicep Infrastructure'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      name: 'DeployBicep'
      displayName: '🚀 Deploy Core Bicep Infrastructure'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(SERVICE_CONNECTION_NAME)'
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(AZURE_RESOURCE_GROUP)
        location: '${{ parameters.azure_location }}'
        templateLocation: 'Linked artifact'
        csmFile: $(AZURE_BICEP_MAIN)
        deploymentMode: 'Incremental'
        deploymentOutputs: 'outputs'
        overrideParameters: >
          -projectName "${{ parameters.project_name }}"
          -environmentName "${{ parameters.environment_name }}"
          -location "${{ parameters.azure_location }}"
          -openAILocation "${{ parameters.azure_location }}"
          -azureClientID "$(AZURE_CLIENT_ID)"
          -azureTenantId "$(AZURE_TENANT_ID)"
          -aspCoreEnvironment "${{ parameters.asp_core_environment }}"
          -kvSetFunctionAppPermissions ${{ lower(parameters.set_kv_function_app_permissions) }}
          -semanticSearchSku "${{ parameters.semantic_search_sku }}"
          -apimAiEndpointOverride "$(APIM_ENDPOINT_OVERRIDE)"
          -apimAiEmbeddingsEndpointOverride "$(APIM_EMBEDDINGS_ENDPOINT_OVERRIDE)"
