name: Validate Bicep templates
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - "infra/**"
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - "infra/**"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Build Bicep
        uses: azure/cli@v2
        with:
          azcliversion: 2.64.0
          inlineScript: |
            # Install dependencies for Bicep
            tdnf install -y icu jq
            # Install and build Bicep templates
            az bicep install
            az config set bicep.use_binary_from_path=false
            az bicep build -f infra/main.bicep --stdout

      - name: Run Security Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
