name: Deploy AgileChat

# Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the Azure Deployment Environment'
        type: choice
        default: 'Development'
        options:
          - Development
          - Test
          - UAT
          - Production
      apiWebAppName:
        description: 'Enter the name of the Azure Web Api'
        type: string
        default: 'agilechat-dev-apiapp'
      uiWebAppName:
        description: 'Azure Web App Name'
        type: string
        default: 'agilechat-dev-webapp'

env:
  AGILE_CHAT_API_SRC: './src/Agile.Chat/Agile.Chat.Api'
  AGILE_CHAT_API_PUB: './publish/Agile.Chat/Agile.Chat.Api'
  AGILE_WEB_SRC: './src/agile-chat-web'
  AGILE_WEB_PUB: './publish/agile-chat-web'
  #VITE_AGILECHAT_API_URL
  #VITE_AZURE_AD_CLIENT_ID
  #VITE_AZURE_AD_TENANT_ID

jobs:
  build-and-deploy-api:
    name: Build and Deploy AgileChat Web API
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        persist-credentials: true

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Agile-Chat-Api - dotnet build and publish
      run: |
        dotnet restore ${{ env.AGILE_CHAT_API_SRC }}
        dotnet build ${{ env.AGILE_CHAT_API_SRC }} --no-restore --configuration Release
        dotnet publish ${{ env.AGILE_CHAT_API_SRC }} -c Release -o ${{ env.AGILE_CHAT_API_PUB }}
      env:
        ENVIRONMENT: ${{ github.event.inputs.environment }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy - Agile-Chat-Api
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ github.event.inputs.apiWebAppName }}
        package: ${{ env.AGILE_CHAT_API_PUB }}

  build-and-deploy-web:
    name: Build and Deploy AgileChat Web UI
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        persist-credentials: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build Agile Chat Web App
      run: |
        cd ${{ env.AGILE_WEB_SRC }}
        npm install
        npm run build

    - name: Create ZIP artifact
      run: |
        cd ${{ env.AGILE_WEB_SRC }}/dist
        zip -r ${{ github.workspace }}/release.zip .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy Agile Chat Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ github.event.inputs.uiWebAppName }}
        package: ${{ github.workspace }}/release.zip