name: Deploy Network Infrastructure

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Enter the Name of the project"
        type: string
        default: "ag-aione-v3"
        required: true
      environment_name:
        description: "Select the application environment name - used to name resources"
        type: choice
        default: "uat"
        options:
          - "dev"
          - "tst"
          - "uat"
          - "prod"
        required: true
      azure_location:
        description: "Select the Azure deployment location"
        type: choice
        default: "australiaeast"
        options:
          - "australiaeast"
          - "australiasoutheast"
        required: true
env:
  AZURE_BICEP_MAIN: "./infra/networking/main.bicep"
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  PROJECT_NAME: ${{ inputs.project_name }}
  AZURE_LOCATION: ${{ inputs.azure_location }}
  # This workflow deploys the core networking infrastructure including:
  # - Virtual Network (VNet) with multiple subnets
  # - Network Security Groups (NSGs) for each subnet
  # - Azure Bastion (if enabled)
  # - Diagnostic settings for monitoring

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    name: Deploy Networking Infrastructure
    environment: ${{ inputs.environment_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep Template
        run: |
          az deployment group validate \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --template-file ${{ env.AZURE_BICEP_MAIN }} \
            --parameters @infra/networking/${{ inputs.environment_name }}.bicepparam \
            --verbose

      - name: Deploy Bicep Infrastructure
        id: deployment
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: bicep-deployment
          scope: resourceGroup
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ vars.AZURE_RESOURCE_GROUP }}
          template-file: ${{ env.AZURE_BICEP_MAIN }}
          parameters-file: infra/networking/${{ inputs.environment_name }}.bicepparam
          parameters: '{"environmentName": "${{ inputs.environment_name }}" }'