name: Deploy AI-One Web App

# Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Select the application environment name - used to name resources"
        type: choice
        default: "dev"
        options:
          - "dev"
          - "tst"
          - "uat"
          - "prod"
        required: true
env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_BICEP_MAIN: "./infra/frontend/webapp.bicep"
  AGILE_WEB_SRC: "./src/agile-chat-web"
  VITE_AGILECHAT_API_URL: ${{ vars.VITE_AGILECHAT_API_URL }}
  VITE_AZURE_AD_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  VITE_AZURE_AD_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    environment: ${{ inputs.environment_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
