name: IaC

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Enter the Name of the project"
        type: string
        default: "ag-aione-v2"
        required: true
      environment_name:
        description: "Select the application environment name - used to name resources"
        type: choice
        default: "dev"
        options:
          - "dev"
          - "tst"
          - "uat"
          - "prod"
        required: true
      azure_location:
        description: "Select the Azure deployment location"
        type: choice
        default: "australiaeast"
        options:
          - "australiaeast"
          - "australiasoutheast"
        required: true
env:
  AZURE_PROJECT_NAME: ag-aione-v2
  AZURE_ENVIRONMENT_NAME: dev
  AZURE_LOCATION: australiaeast
  AZURE_OPENAI_LOCATION: australiaeast
  AZURE_BICEP_MAIN: "./infra/main.bicep"
  # AZURE_SUBSCRIPTION_ID
  # AZURE_CLIENT_ID
  # AZURE_TENANT_ID
  # AZURE_RESOURCE_GROUP
  # APIM_ENDPOINT_OVERRIDE (optional but needed to be defined in variables as empty)
  # APIM_EMBEDDINGS_ENDPOINT_OVERRIDE (optional but needed to be defined in variables as empty)

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    environment: ${{ inputs.environment_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep Infrastructure
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          template: ${{ env.AZURE_BICEP_MAIN }}
          parameters: ./infra/dev.parameters.json
          includeAdditionalFiles: |
            ./infra/blob-storage-containers.json
            ./infra/openai-models.json
